// Standalone mock dataset for WildLumina Frontend

export const mockDetections = [
  {
    id: 101,
    animalName: 'Bengal Tiger',
    confidence: 0.964,
    detectionTime: '2026-08-10T08:45:12Z',
    location: 'Zone 1 - Sector 4 (Mudumalai)',
    status: 'CONFIRMED',
    imageUrl: '/assets/images/tiger_detection.png',
    bbox: { x: 120, y: 80, width: 340, height: 260 },
    speciesCategory: 'Carnivore',
    conservationStatus: 'Endangered',
    rareSpecies: true,
    sensorId: 'CAM-WL-014',
  },
  {
    id: 102,
    animalName: 'Asian Elephant',
    confidence: 0.942,
    detectionTime: '2026-08-10T08:12:05Z',
    location: 'Zone 2 - Corridor B (Bandipur)',
    status: 'CONFIRMED',
    imageUrl: '/assets/images/elephant_detection.png',
    bbox: { x: 150, y: 60, width: 400, height: 320 },
    speciesCategory: 'Herbivore',
    conservationStatus: 'Vulnerable',
    rareSpecies: false,
    sensorId: 'CAM-WL-008',
  },
  {
    id: 103,
    animalName: 'Indian Leopard',
    confidence: 0.891,
    detectionTime: '2026-08-10T07:30:22Z',
    location: 'Zone 1 - Sector 2 (Anamalai)',
    status: 'PENDING',
    imageUrl: '/assets/images/tiger_detection.png',
    bbox: { x: 90, y: 110, width: 280, height: 210 },
    speciesCategory: 'Carnivore',
    conservationStatus: 'Vulnerable',
    rareSpecies: true,
    sensorId: 'CAM-WL-022',
  },
  {
    id: 104,
    animalName: 'Spotted Deer',
    confidence: 0.985,
    detectionTime: '2026-08-10T06:50:11Z',
    location: 'Zone 3 - Range East (Nagarhole)',
    status: 'CONFIRMED',
    imageUrl: '/assets/images/elephant_detection.png',
    bbox: { x: 200, y: 140, width: 210, height: 190 },
    speciesCategory: 'Herbivore',
    conservationStatus: 'Least Concern',
    rareSpecies: false,
    sensorId: 'CAM-WL-003',
  },
  {
    id: 105,
    animalName: 'Indian Gaur',
    confidence: 0.878,
    detectionTime: '2026-08-10T05:15:40Z',
    location: 'Zone 2 - Sector 1 (Wayanad)',
    status: 'CONFIRMED',
    imageUrl: '/assets/images/wildlife_bg.png',
    bbox: { x: 100, y: 90, width: 360, height: 280 },
    speciesCategory: 'Herbivore',
    conservationStatus: 'Vulnerable',
    rareSpecies: false,
    sensorId: 'CAM-WL-019',
  },
  {
    id: 106,
    animalName: 'Sloth Bear',
    confidence: 0.720,
    detectionTime: '2026-08-09T22:14:09Z',
    location: 'Zone 4 - Western Border',
    status: 'PENDING',
    imageUrl: '/assets/images/tiger_detection.png',
    bbox: { x: 180, y: 120, width: 250, height: 220 },
    speciesCategory: 'Omnivore',
    conservationStatus: 'Vulnerable',
    rareSpecies: true,
    sensorId: 'CAM-WL-031',
  },
]

export const mockAlerts = [
  {
    id: 1,
    alertType: 'Poaching Risk Alert',
    species: 'Bengal Tiger',
    severity: 'HIGH',
    confidence: 0.964,
    createdAt: '2026-08-10T08:45:12Z',
    status: 'ACTIVE',
    location: 'Zone 1 - Sector 4',
    description: 'Rare apex predator detected in night-vision camera near boundary perimeter.',
  },
  {
    id: 2,
    alertType: 'Human-Wildlife Conflict Warning',
    species: 'Asian Elephant',
    severity: 'HIGH',
    confidence: 0.942,
    createdAt: '2026-08-10T08:12:05Z',
    status: 'ACKNOWLEDGED',
    location: 'Zone 2 - Village Border Corridor B',
    description: 'Herd moving towards agricultural field fence line.',
  },
  {
    id: 3,
    alertType: 'Low Confidence Detection',
    species: 'Sloth Bear',
    severity: 'LOW',
    confidence: 0.720,
    createdAt: '2026-08-09T22:14:09Z',
    status: 'ACTIVE',
    location: 'Zone 4 - Western Border',
    description: 'Partial view detection under poor lighting conditions. Verification required.',
  },
  {
    id: 4,
    alertType: 'Movement Intrusion Alert',
    species: 'Indian Leopard',
    severity: 'MEDIUM',
    confidence: 0.891,
    createdAt: '2026-08-10T07:30:22Z',
    status: 'RESOLVED',
    location: 'Zone 1 - Sector 2',
    description: 'Leopard crossed forest patrol road. Officer dispatched and clear.',
  },
]

export const mockMonitoringStatus = {
  folderMonitoring: 'ACTIVE',
  aiModelStatus: 'LOADED',
  modelName: 'WildLumina-YOLOv8x-v2.1',
  incomingFolderPath: 'datasets/incoming_images/',
  lastProcessedImage: 'IMG_20260810_084512_014.jpg',
  lastDetectedAnimal: 'Bengal Tiger',
  lastConfidence: 0.964,
  lastDetectionTime: '2026-08-10T08:45:12Z',
  imagesProcessedToday: 142,
  detectionsToday: 89,
  activeAlertsCount: 2,
}

export const mockUsers = [
  { id: 1, loginId: 'ADMIN001', fullName: 'Dr. Rajesh V. Sharma', role: 'SYSTEM_ADMIN', email: 'r.sharma@wildlumina.gov.in', phone: '+91 98765 43210', officeName: 'Central Wildlife HQ, Delhi', status: 'ACTIVE' },
  { id: 2, loginId: 'FO1001', fullName: 'Karan Singh, IFS', role: 'FOREST_OFFICER', email: 'karan.singh@forest.gov.in', phone: '+91 98123 45678', forestZone: 'Southern Western Ghats', forestRange: 'Mudumalai Range', stationName: 'Theppakadu Checkpost', status: 'ACTIVE' },
  { id: 3, loginId: 'RES1001', fullName: 'Dr. Ananya Nair', role: 'RESEARCHER', email: 'ananya.nair@wii.gov.in', phone: '+91 97654 32109', organization: 'Wildlife Institute of India', department: 'Ecological AI & Biometrics', status: 'ACTIVE' },
  { id: 4, loginId: 'FO1002', fullName: 'Priya Mukherjee', role: 'FOREST_OFFICER', email: 'p.mukherjee@forest.gov.in', phone: '+91 98345 67890', forestZone: 'Nilgiri Biosphere', forestRange: 'Bandipur Range', stationName: 'Moolehole Checkpost', status: 'ACTIVE' },
  { id: 5, loginId: 'RES1002', fullName: 'Prof. Vikram Roy', role: 'RESEARCHER', email: 'v.roy@iisc.ac.in', phone: '+91 99112 23344', organization: 'IISc Center for Ecological Sciences', department: 'Computational Ecology', status: 'INACTIVE' },
]

export const mockAdminStats = {
  totalUsers: 24,
  forestOfficers: 14,
  researchers: 8,
  systemAdmins: 2,
  imagesProcessed: 18450,
  totalDetections: 12380,
  activeAlerts: 3,
  aiModelStatus: 'LOADED',
  folderMonitoringStatus: 'ACTIVE',
  speciesDistribution: [
    { name: 'Spotted Deer', count: 5420, fill: '#2E7D32' },
    { name: 'Asian Elephant', count: 2840, fill: '#4CAF50' },
    { name: 'Indian Gaur', count: 2110, fill: '#7B68EE' },
    { name: 'Bengal Tiger', count: 890, fill: '#F57C00' },
    { name: 'Indian Leopard', count: 740, fill: '#D32F2F' },
    { name: 'Sloth Bear', count: 380, fill: '#9C27B0' },
  ],
  dailyDetections: [
    { date: 'Mon', detections: 240, images: 380 },
    { date: 'Tue', detections: 310, images: 420 },
    { date: 'Wed', detections: 280, images: 390 },
    { date: 'Thu', detections: 410, images: 580 },
    { date: 'Fri', detections: 390, images: 510 },
    { date: 'Sat', detections: 480, images: 620 },
    { date: 'Sun', detections: 520, images: 710 },
  ],
  systemActivity: [
    { time: '08:00', cpu: 22, memory: 45, storage: 68 },
    { time: '08:15', cpu: 38, memory: 48, storage: 68 },
    { time: '08:30', cpu: 65, memory: 52, storage: 69 },
    { time: '08:45', cpu: 84, memory: 58, storage: 69 },
    { time: '09:00', cpu: 42, memory: 54, storage: 70 },
  ],
}

export const mockResearcherStats = {
  trainingImages: 45200,
  validationImages: 8500,
  testingImages: 6200,
  numberOfClasses: 12,
  currentModel: 'WildLumina-YOLOv8x-v2.1',
  precision: 0.948,
  recall: 0.926,
  mAP50: 0.954,
  mAP50_95: 0.812,
  epochMetrics: [
    { epoch: 10, loss: 0.42, map50: 0.72, valLoss: 0.45 },
    { epoch: 20, loss: 0.31, map50: 0.81, valLoss: 0.35 },
    { epoch: 30, loss: 0.22, map50: 0.88, valLoss: 0.26 },
    { epoch: 40, loss: 0.16, map50: 0.92, valLoss: 0.19 },
    { epoch: 50, loss: 0.11, map50: 0.954, valLoss: 0.14 },
  ],
  classPerformance: [
    { class: 'Bengal Tiger', samples: 1200, precision: 0.965, recall: 0.942, map50: 0.971 },
    { class: 'Asian Elephant', samples: 3400, precision: 0.972, recall: 0.955, map50: 0.980 },
    { class: 'Indian Leopard', samples: 950, precision: 0.912, recall: 0.885, map50: 0.924 },
    { class: 'Spotted Deer', samples: 8200, precision: 0.981, recall: 0.974, map50: 0.989 },
    { class: 'Indian Gaur', samples: 2900, precision: 0.945, recall: 0.930, map50: 0.956 },
    { class: 'Sloth Bear', samples: 610, precision: 0.890, recall: 0.840, map50: 0.885 },
  ],
}
